version: '2.3'


services:
  fhem:
    depends_on:
      - "db"

  db:
    image: linuxserver/mariadb:10.6.12
    container_name: mariadb
    environment:
     - PGID=1003
     - REMOTE_SQL="https://svn.fhem.de/trac/export/HEAD/trunk/fhem/contrib/dblog/db_create_mysql.sql"
     - TZ=Europe/Berlin
    volumes:
      - vol-fhem-dblog:/config

    restart: unless-stopped
    networks:
     - fhem_docker_net

volumes:
  vol-fhem-dblog:

