version: '2.3'

networks:
  fhem_net:
    driver: bridge
    # enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 172.27.0.0/28
          gateway: 172.27.0.1
        - subnet: fd00:0:0:0:27::/80
          gateway: fd00:0:0:0:27::1

services:
  fhem:
    image:  ghcr.io/fhem/fhem/fhem-minimal-docker:3.1.3-bullseye
    restart: always
    networks:
      - fhem_net
    ports:
      - "8083:8083"
    volumes:
      - vol-fhem-app:/opt/fhem/

    mem_limit: 1gb
    memswap_limit: 1gb
    environment:
      FHEM_UID: 6061
      FHEM_GID: 6061
      TIMEOUT: 10
      RESTART: 1 
      TZ: Europe/Berlin


volumes:
  vol-fhem-app: